# Site settings
title: X-burger
description: 'X-Burger são minhas anotações das coisa que venho aprendendo ao longo desses anos com o github e faço questão de compartilhar. </br> Aqui você vai descobrir muitas coisas interessantes nesse universo da tecnologia da informação. </br> Fique a vontade para pesquisar nosso blog que esta em desenvolvimento contínuou. </br> </br> Se quiser nos pagar um café fique a vontade, BTC: 37PBho29TdvZMkUsAkrPgCwdofPKAAGDCG '
url: ''
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Marcio Sieburger'
  email: marcio@sieburger.link
  twitter_username: sieburgerr
  facebook_username: marcio.sieburger
  github_username:  x-burger
  linkedin_username:  marcio-sieburger

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
#  -
#    scope:
#      path: ''
#      type: 'pages'
#    values:
#      layout: 'page'

# Build settings
destination: _site
paginate: 20
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
